const _ = require("lodash");
const loremIpsum = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A erat nam at lectus urna duis. Adipiscing diam donec adipiscing tristique. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Ornare suspendisse sed nisi lacus sed viverra tellus in hac. Nulla pellentesque dignissim enim sit amet. Quam nulla porttitor massa id neque aliquam. Lobortis feugiat vivamus at augue eget arcu dictum. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Velit sed ullamcorper morbi tincidunt ornare. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Ut pharetra sit amet aliquam id. Eget aliquet nibh praesent tristique magna. Cursus sit amet dictum sit amet justo donec.",
  "Risus ultricies tristique nulla aliquet enim tortor.Potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed.Curabitur gravida arcu ac tortor dignissim.Condimentum lacinia quis vel eros donec ac odio tempor orci.Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare.Ut venenatis tellus in metus.Scelerisque eu ultrices vitae auctor.Sem nulla pharetra diam sit.Ante metus dictum at tempor commodo ullamcorper a lacus.Vestibulum rhoncus est pellentesque elit.Urna molestie at elementum eu facilisis sed.Semper viverra nam libero justo.",
  "Ac tortor vitae purus faucibus ornare suspendisse sed nisi lacus.Volutpat lacus laoreet non curabitur gravida arcu ac tortor.Cras fermentum odio eu feugiat pretium.Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae.Enim nunc faucibus a pellentesque sit amet porttitor eget.Dictum non consectetur a erat nam at lectus.Iaculis urna id volutpat lacus laoreet.Vitae turpis massa sed elementum tempus egestas sed sed risus.Tortor aliquam nulla facilisi cras fermentum odio eu.Quis lectus nulla at volutpat diam ut venenatis tellus in.Turpis massa tincidunt dui ut ornare.Neque convallis a cras semper auctor.Lorem mollis aliquam ut porttitor leo.Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar.Non diam phasellus vestibulum lorem.",
  "Risus feugiat in ante metus dictum at.Turpis massa tincidunt dui ut ornare lectus sit amet.Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget.Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit.Varius quam quisque id diam vel quam.Commodo ullamcorper a lacus vestibulum sed arcu non.Adipiscing elit ut aliquam purus.Vel facilisis volutpat est velit egestas dui id.Convallis tellus id interdum velit laoreet id donec.Diam maecenas sed enim ut.Volutpat maecenas volutpat blandit aliquam etiam erat velit.Cras semper auctor neque vitae tempus quam pellentesque.Curabitur gravida arcu ac tortor dignissim convallis.At elementum eu facilisis sed odio morbi quis commodo.Quam id leo in vitae turpis massa sed.Ornare suspendisse sed nisi lacus sed viverra.Nisi scelerisque eu ultrices vitae auctor eu.Nisi lacus sed viverra tellus.Interdum velit laoreet id donec ultrices tincidunt arcu non.",
  "Nec ullamcorper sit amet risus nullam eget.Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis.Commodo odio aenean sed adipiscing diam donec.Et odio pellentesque diam volutpat commodo sed egestas.Potenti nullam ac tortor vitae purus faucibus ornare.Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit.At tellus at urna condimentum mattis.Rhoncus urna neque viverra justo.Sit amet porttitor eget dolor morbi.Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida.Sit amet tellus cras adipiscing enim eu turpis.Tellus molestie nunc non blandit massa.Tristique risus nec feugiat in fermentum posuere.Mattis rhoncus urna neque viverra justo nec.At auctor urna nunc id cursus metus.Aliquam faucibus purus in massa tempor nec feugiat nisl pretium.Cras ornare arcu dui vivamus arcu felis bibendum ut tristique.Mi in nulla posuere sollicitudin aliquam ultrices.",
  "Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget.Sit amet consectetur adipiscing elit pellentesque habitant morbi.Tincidunt augue interdum velit euismod in pellentesque massa placerat.Eu lobortis elementum nibh tellus molestie.Viverra tellus in hac habitasse platea dictumst.Massa sed elementum tempus egestas sed sed risus pretium.Id interdum velit laoreet id donec.Pellentesque id nibh tortor id aliquet lectus proin nibh.Ornare suspendisse sed nisi lacus sed.Nunc mattis enim ut tellus elementum.Nunc consequat interdum varius sit amet mattis vulputate enim nulla.Iaculis at erat pellentesque adipiscing commodo elit at.Non enim praesent elementum facilisis leo vel fringilla.",
  "Tellus integer feugiat scelerisque varius.Lobortis mattis aliquam faucibus purus in massa.Sed enim ut sem viverra.Lobortis mattis aliquam faucibus purus in massa tempor nec.Habitant morbi tristique senectus et netus et.In iaculis nunc sed augue lacus viverra.Ipsum nunc aliquet bibendum enim facilisis.Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla.Magna ac placerat vestibulum lectus mauris ultrices eros in cursus.Tempus iaculis urna id volutpat.Nullam eget felis eget nunc.Massa id neque aliquam vestibulum morbi blandit.Imperdiet dui accumsan sit amet.Vel risus commodo viverra maecenas accumsan lacus vel.Neque laoreet suspendisse interdum consectetur.",
  "Tincidunt dui ut ornare lectus.Ac turpis egestas integer eget aliquet nibh praesent tristique magna.Pretium vulputate sapien nec sagittis aliquam malesuada bibendum.Orci sagittis eu volutpat odio facilisis mauris.Posuere ac ut consequat semper viverra nam.Justo nec ultrices dui sapien eget mi proin.Id aliquet lectus proin nibh nisl condimentum id venenatis.Nulla pellentesque dignissim enim sit amet.Commodo nulla facilisi nullam vehicula.Etiam non quam lacus suspendisse faucibus interdum.Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis.Mattis nunc sed blandit libero volutpat.Nulla pharetra diam sit amet nisl.Nibh ipsum consequat nisl vel pretium lectus quam id.Consectetur adipiscing elit duis tristique sollicitudin nibh sit.",
  "Neque aliquam vestibulum morbi blandit cursus risus.Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada.Ac orci phasellus egestas tellus rutrum tellus pellentesque eu.Vitae purus faucibus ornare suspendisse sed nisi.Id consectetur purus ut faucibus pulvinar elementum.Gravida in fermentum et sollicitudin ac orci phasellus egestas.Gravida in fermentum et sollicitudin ac orci phasellus.In fermentum et sollicitudin ac orci phasellus.Aliquet porttitor lacus luctus accumsan.Id aliquet risus feugiat in ante metus.Eget est lorem ipsum dolor.Cras fermentum odio eu feugiat pretium nibh.Fringilla ut morbi tincidunt augue interdum velit.Sed blandit libero volutpat sed cras.Turpis nunc eget lorem dolor sed viverra ipsum.Augue eget arcu dictum varius.Iaculis urna id volutpat lacus laoreet non curabitur.",
  "Ac auctor augue mauris augue neque gravida in.Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt.Feugiat in fermentum posuere urna nec tincidunt praesent.Vivamus arcu felis bibendum ut tristique et.Nulla facilisi cras fermentum odio eu feugiat.Habitant morbi tristique senectus et netus et malesuada.Diam volutpat commodo sed egestas egestas fringilla phasellus.Phasellus faucibus scelerisque eleifend donec pretium vulputate.Nulla pellentesque dignissim enim sit amet venenatis urna cursus.Maecenas volutpat blandit aliquam etiam erat velit scelerisque in.Ipsum dolor sit amet consectetur adipiscing elit."
];

module.exports = function(numOfParagraph, asArray = false) {
  if (numOfParagraph > loremIpsum.length) numOfParagraph = loremIpsum.length;
  const arr = _.slice(loremIpsum, 0, numOfParagraph - 1);
  if (asArray) return arr;
  else return _.join(arr, "\n"); //is this enough?
};
